In [1]:
import pandas as pd


!which python
!where python

'which' is not recognized as an internal or external command,
operable program or batch file.

c:\Repo\recommendersystems\RS\Scripts\python.exe
C:\Users\willi\AppData\Local\Programs\Python\Python312\python.exe
C:\Users\willi\AppData\Local\Microsoft\WindowsApps\python.exe

In [2]:


danish_articles = pd.read_parquet('../data/ebnerd_large/articles.parquet', engine='pyarrow')
danish_behaviors = pd.read_parquet('../data/ebnerd_large/train/behaviors.parquet', engine='pyarrow')
danish_history = pd.read_parquet('../data/ebnerd_large/train/history.parquet', engine='pyarrow')
mind_articles = pd.read_csv("../data/MINDlarge_train/news.tsv", sep="\t")

In [3]:
mind_articles["lifestyle"].unique()
mind_articles["lifestyleroyals"].unique()

,N88753,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, and Prince Philip Swear By","Shop the notebooks, jackets, and more that the royals can't live without.",https://assets.msn.com/labs/mind/AAGH0ET.html,"[{""Label"": ""Prince Philip, Duke of Edinburgh"", ""Type"": ""P"", ""WikidataId"": ""Q80976"", ""Confidence"": 1.0, ""OccurrenceOffsets"": [48], ""SurfaceForms"": [""Prince Philip""]}, {""Label"": ""Charles, Prince of Wales"", ""Type"": ""P"", ""WikidataId"": ""Q43274"", ""Confidence"": 1.0, ""OccurrenceOffsets"": [28], ""SurfaceForms"": [""Prince Charles""]}, {""Label"": ""Elizabeth II"", ""Type"": ""P"", ""WikidataId"": ""Q9682"", ""Confidence"": 0.97, ""OccurrenceOffsets"": [11], ""SurfaceForms"": [""Queen Elizabeth""]}]",[]
0,N45436,news,newsscienceandtechnology,Walmart Slashes Prices on Last-Generation iPads,Apple's new iPad releases bring big deals on l...,https://assets.msn.com/labs/mind/AABmf2I.html,"[{""Label"": ""IPad"", ""Type"": ""J"", ""WikidataId"": ...","[{""Label"": ""IPad"", ""Type"": ""J"", ""WikidataId"": ..."
1,N23144,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,https://assets.msn.com/labs/mind/AAB19MK.html,"[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik...","[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik..."
2,N86255,health,medical,Dispose of unwanted prescription drugs during ...,NaN,https://assets.msn.com/labs/mind/AAISxPN.html,"[{""Label"": ""Drug Enforcement Administration"", ...",[]
3,N93187,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,https://assets.msn.com/labs/mind/AAJgNsz.html,[],"[{""Label"": ""Ukraine"", ""Type"": ""G"", ""WikidataId..."
4,N75236,health,voices,I Was An NBA Wife. Here's How It Affected My M...,"I felt like I was a fraud, and being an NBA wi...",https://assets.msn.com/labs/mind/AACk2N6.html,[],"[{""Label"": ""National Basketball Association"", ..."
...,...,...,...,...,...,...,...,...
101521,N115249,sports,more_sports,St. Dominic soccer player tries to kick cancer...,"Sometimes, what happens on the sidelines can b...",https://assets.msn.com/labs/mind/BBWzQnK.html,[],[]
101522,N64337,finance,finance-real-estate,Mansion Monday: Contemporary Des Moines home i...,Among the perks of this unique Des Moines home...,https://assets.msn.com/labs/mind/BBWzQq8.html,"[{""Label"": ""Des Moines, Iowa"", ""Type"": ""G"", ""W...","[{""Label"": ""Des Moines, Iowa"", ""Type"": ""G"", ""W..."
101523,N100102,sports,soccer_epl,How the Sounders won MLS Cup,"Mark, Jeremiah and Casey were so excited they ...",https://assets.msn.com/labs/mind/BBWzQuK.html,"[{""Label"": ""MLS Cup"", ""Type"": ""U"", ""WikidataId...",[]
101524,N74617,autos,autossports,Best Sports Car Deals for October,NaN,https://assets.msn.com/labs/mind/BBy5rVe.html,"[{""Label"": ""Peugeot RCZ"", ""Type"": ""V"", ""Wikida...",[]
101525,N56840,sports,more_sports,Shall we dance: Sports stars shake their leg,NaN,https://assets.msn.com/labs/mind/BBzMpnG.html,[],[]

In [4]:
danish_articles
# danish_behaviors
# danish_history

,article_id,title,subtitle,last_modified_time,premium,body,published_time,image_ids,article_type,url,...,entity_groups,topics,category,subcategory,category_str,total_inviews,total_pageviews,total_read_time,sentiment_score,sentiment_label
0,3000022,Hanks beskyldt for mishandling,Tom Hanks har angiveligt mishandlet sin afdÃ¸de...,2023-06-29 06:20:32,False,Tom Hanks skulle angiveligt have mishandlet si...,2006-09-20 09:24:18,[3518381],article_default,https://ekstrabladet.dk/underholdning/udlandke...,...,[PER],"[Kriminalitet, Kendt, Underholdning, Personfar...",414,[432],underholdning,NaN,NaN,NaN,0.9911,Negative
1,3000063,Bostrups aske spredt i FuresÃ¸en,StudievÃ¦rten blev mindet med glad festlighed,2023-06-29 06:20:32,False,StrÃ¥lende sensommersol. Jazzede toner. Glas me...,2006-09-24 07:45:30,"[3170935, 3170939]",article_default,https://ekstrabladet.dk/nyheder/samfund/articl...,...,[],"[Kendt, Underholdning, Begivenhed, Personlig b...",118,[133],nyheder,NaN,NaN,NaN,0.5155,Neutral
2,3000613,Jesper Olsen ramt af hjerneblÃ¸dning,Den tidligere danske landsholdsspiller i fodbo...,2023-06-29 06:20:33,False,"Jesper Olsen, der er noteret for 43 kampe pÃ¥ d...",2006-05-09 11:29:00,[3164998],article_default,https://ekstrabladet.dk/sport/fodbold/landshol...,...,"[LOC, PER, PER, PER]","[Kendt, Sport, Fodbold, Sundhed, Sygdom og beh...",142,"[196, 271]",sport,NaN,NaN,NaN,0.9876,Negative
3,3000700,Madonna toplÃ¸s med heste,47-Ã¥rige Madonna poserer bÃ¥de toplÃ¸s og sammen...,2023-06-29 06:20:33,False,Skal du have stillet Madonna-sulten inden konc...,2006-05-04 11:03:12,[3172046],article_default,https://ekstrabladet.dk/underholdning/udlandke...,...,[],"[Kendt, Livsstil, Underholdning]",414,[432],underholdning,NaN,NaN,NaN,0.8786,Neutral
4,3000840,Otto Brandenburg er dÃ¸d,Sangeren og skuespilleren Otto Brandenburg er ...,2023-06-29 06:20:33,False,"'Og lidt for Susanne, Birgitte og Hanne... ' '...",2007-03-01 18:34:00,[3914446],article_default,https://ekstrabladet.dk/nyheder/samfund/articl...,...,[],"[Kendt, Underholdning, Begivenhed, Personlig b...",118,[133],nyheder,NaN,NaN,NaN,0.9468,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125536,9803505,Flyvende Antonsen knuser topspiller,"Verdens nummer syv, Chou Tien-Chen, fik ikke e...",2023-06-29 06:49:26,False,Anders Antonsen har holdt pause fra badmintonb...,2023-06-08 05:54:06,[9803516],article_default,https://ekstrabladet.dk/sport/anden_sport/badm...,...,"[PER, PROD, PER, PER, MISC, MISC, PER, PER, LO...","[Kendt, Begivenhed, Sport, Ketcher- og batspor...",142,"[327, 330]",sport,13320.0,959.0,55691.0,0.8884,Positive
125537,9803510,Nedschroef Langeskov udbetalte udbytte pÃ¥ toci...,Hos Nedschroef Langeskov ApS udbetalte man i d...,2023-06-29 06:49:26,False,Et udbytte pÃ¥ 30 millioner kroner blev i sidst...,2023-06-08 05:48:51,[9803509],article_default,https://ekstrabladet.dk/auto/magna/regnskaber/...,...,"[LOC, ORG, LOC, LOC, ORG, PER]","[Erhverv, Privat virksomhed, Ã˜konomi]",2889,"[2890, 2900]",auto,12.0,1.0,25.0,0.8723,Negative
125538,9803525,"Dansk skuespiller: - Jeg nÃ¦gtede, at jeg var syg",Julie R. Ã˜lgaard fik akut kejsersnit og fÃ¸dte ...,2023-06-29 06:49:26,False,"Mens hun lÃ¥ sÃ¸vnlÃ¸s, lÃ¸d kakofonien fra baggÃ¥r...",2023-06-08 06:45:46,"[9803518, 9803519, 9803520, 9803521, 9803522, ...",article_default,https://ekstrabladet.dk/underholdning/dkkendte...,...,"[PER, PROD, PER, PER, PER, PER, MISC]","[Kendt, Livsstil, Familieliv, Underholdning, F...",414,[425],underholdning,315391.0,50361.0,2550671.0,0.7737,Negative
125539,9803560,SÃ¥ slemt er det: 14.000 huse er oversvÃ¸mmet,Tusindvis af huse stÃ¥r under vand i Kherson-re...,2023-06-29 06:49:26,False,Et omrÃ¥de pÃ¥ omkring 600 kvadratkilometer stÃ¥r...,2023-06-08 06:25:42,None,article_default,https://ekstrabladet.dk/nyheder/saa-slemt-er-d...,...,"[LOC, LOC, LOC, PROD, PER, LOC, ORG, ORG, LOC]","[International politik, Katastrofe, StÃ¸rre kat...",118,[],nyheder,21318.0,1237.0,67514.0,0.9927,Negative
125540,9803607,Aktion mod svindlere: Seks personer anholdt,Flere kvinder er ifÃ¸lge politiet blevet svindl...,2023-06-29 06:49:26,False,Mindst otte personer er blevet anholdt og sigt...,2023-06-08 06:54:53,[9803906],article_default,https://ekstrabladet.dk/krimi/aktion-mod-svind...,...,"[PER, PER, PER, LOC, ORG, LOC, LOC, PER, PER, ...","[Kriminalitet, Bedrageri]",140,[],krimi,331057.0,79590.0,3694760.0,0.9948,Negative